name: CI

on:
  pull_request:
  push:
    branches:
      - master
      # Bors : strict mode for your CI/CD
      # https://bors.tech/documentation/getting-started/
      - staging # This is where pull requests from "bors r+" are built.
      - trying # This is where pull requests from "bors try" are built.

jobs:
  test:
    name: Build and test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    # see https://github.com/actions/starter-workflows/blob/master/ci/gradle.yml
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Run test
      run: ./gradlew test
